paths:
  /price:
    post:
      tags:
        - price
      summary: Create a new instance of the model and persist it into the data source.
      operationId: price.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/price'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
    patch:
      tags:
        - price
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: price.patchOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/price'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
    put:
      tags:
        - price
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: price.replaceOrCreate__put_price
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/price'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
    get:
      tags:
        - price
      summary: Find all instances of the model matched by filter from the data source.
      operationId: price.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/price'
      deprecated: false
  /price/replaceOrCreate:
    post:
      tags:
        - price
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: price.replaceOrCreate__post_price_replaceOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/price'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
  /price/upsertWithWhere:
    post:
      tags:
        - price
      summary: Update an existing model instance or insert a new one into the data source based on the where criteria.
      operationId: price.upsertWithWhere
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/price'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
  '/price/{id}/exists':
    get:
      tags:
        - price
      summary: Check whether a model instance exists in the data source.
      operationId: 'price.exists__get_price_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/price/{id}':
    head:
      tags:
        - price
      summary: Check whether a model instance exists in the data source.
      operationId: 'price.exists__head_price_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - price
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: price.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: 'Filter defining fields and include - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
    put:
      tags:
        - price
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: 'price.replaceById__put_price_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/price'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
    delete:
      tags:
        - price
      summary: 'Delete a model instance by {{id}} from the data source.'
      operationId: price.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    patch:
      tags:
        - price
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: price.prototype.patchAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/price'
        - name: id
          in: path
          description: price id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
  '/price/{id}/replace':
    post:
      tags:
        - price
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: 'price.replaceById__post_price_{id}_replace'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/price'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
  /price/findOne:
    get:
      tags:
        - price
      summary: Find first instance of the model matched by filter from the data source.
      operationId: price.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/price'
      deprecated: false
  /price/update:
    post:
      tags:
        - price
      summary: 'Update instances of the model matched by {{where}} from the data source.'
      operationId: price.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/price'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Information related to the outcome of the operation
            type: object
            properties:
              count:
                description: The number of instances updated
                type: number
                format: double
      deprecated: false
  /price/count:
    get:
      tags:
        - price
      summary: Count instances of the model matched by where from the data source.
      operationId: price.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
definitions:
  price:
    properties:
      product-id:
        type: string
      price:
        default: 0
        type: number
        format: double
    required:
      - product-id
    additionalProperties: false
  x-any:
    properties: {}
basePath: ''
swagger: '2.0'
info:
  x-ibm-name: pricing
  version: 1.0.0
  title: pricing
schemes:
  - https
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
